import type { SearchResponse } from "@/types/domain";
import { bottleneckMarkdown } from "./bottleneck";
import { rooflineMarkdown } from "./roofline";
import { energyMarkdown } from "./energy";
import { fusionMarkdown, analyzeFusion } from "./fusion";
import { validityMarkdown } from "./validity";

export function generateReportMarkdown(res: SearchResponse): string {
  const h = res.request.hardware;
  const lines: string[] = [];
  lines.push(`# TileForge 분석 보고서`, "", `생성 시각: ${new Date().toISOString()}`, "");
  lines.push(`## 1. 하드웨어 설정`);
  lines.push(`- 이름: ${h.name}`);
  lines.push(`- 배열 크기: ${h.arrayRows} x ${h.arrayCols}`);
  lines.push(`- 동작 주파수: ${h.frequencyMHz} MHz`);
  lines.push(`- SRAM: ${h.sramKB} KiB`);
  lines.push(`- 데이터플로우: ${h.dataflow}`);
  lines.push(`- 메모리 대역폭: ${h.memoryBandwidthGBs ?? "미설정"} GB/s`);
  lines.push(`- 디스패치 오버헤드: ${h.dispatchOverheadUs ?? "미설정"} us`);
  lines.push("");
  const suite = (res as any).estimatorSuite;
  lines.push(`## 2. 전체 요약`);
  lines.push(`- 전체 예상 사이클: ${res.summary.totalCycles.toLocaleString()}`);
  lines.push(`- 전체 예상 실행 시간: ${res.summary.totalTimeUs.toFixed(3)} us`);
  lines.push(`- 평균 PE 사용률: ${(res.summary.meanUtilization*100).toFixed(2)}%`);
  lines.push(`- 평균 패딩 비율: ${(res.summary.meanPaddingRatio*100).toFixed(2)}%`);
  lines.push(`- 병목 연산: ${res.summary.bottleneckOp}`);
  lines.push(`- 예상 에너지: ${res.energy?.totalEnergyUJ.toFixed(2) ?? "해당 없음"} uJ`);
  if (suite?.applied) {
    lines.push(`- Learned Estimator Suite: 적용됨 (${suite.recommended}, samples=${suite.modelSamples?.toLocaleString?.() ?? suite.modelSamples})`);
    lines.push(`- Analytical baseline cycle: ${suite.totalAnalyticalCycles.toLocaleString()}`);
    lines.push(`- Learned 보정 계수 평균: ×${suite.averageCycleFactor.toFixed(3)}`);
  } else {
    lines.push(`- Learned Estimator Suite: 미적용`);
  }
  lines.push("");
  lines.push(`## 2-1. 실제 외부 도구 반영 상태`);
  lines.push(`**최종 판정: 대기 중**`);
  lines.push("");
  lines.push(`- **TileForge estimator**: 적용됨`);
  lines.push(`  - 근거: 전체 예상 cycle ${res.summary.totalCycles.toLocaleString()}${suite?.applied ? ` (analytical ${suite.totalAnalyticalCycles.toLocaleString()}에서 learned 보정)` : ""}`);
  lines.push(`- **SCALE-Sim**: 대기 중`);
  lines.push(`  - 근거: full-pipeline 완료 후 실제 COMPUTE_REPORT.csv 파싱값으로 자동 갱신됩니다.`);
  lines.push(`- **IREE compile**: 대기 중`);
  lines.push(`  - 근거: full-pipeline 완료 후 실제 model.vmfb 생성 결과로 자동 갱신됩니다.`);
  lines.push(`- **외부 검증 갱신**: 대기 중`);
  lines.push(`  - 근거: full-pipeline이 완료되면 이 보고서와 상세 검증 부록이 함께 갱신됩니다.`);
  lines.push("");
  lines.push(`## 2-2. 예측 결과와 실제 실행 결과 비교`);
  lines.push(`| 항목 | Analytical estimator | Learned estimator | SCALE-Sim 실제 실행 | 해석 |`);
  lines.push(`|---|---:|---:|---:|---|`);
  lines.push(`| 전체 cycle | ${suite?.applied ? suite.totalAnalyticalCycles.toLocaleString() : res.summary.totalCycles.toLocaleString()} | ${res.summary.totalCycles.toLocaleString()} | 대기 중 | ${suite?.applied ? "활성 Estimator Suite 모델이 ranking/report cycle에 반영되었습니다." : "Learned 모델 미적용 상태입니다."} |`);
  lines.push("");
  lines.push(`- 분석: 현재 보고서는 estimator 미리보기입니다. full-pipeline 완료 후에는 SCALE-Sim cycle, 차이, 비율, layer별 cycle 상위 항목이 이 섹션에 자동으로 표시됩니다.`);
  lines.push(`- 주의: IREE compile 성공은 컴파일 가능성 검증이며 cycle 측정값은 SCALE-Sim 결과를 기준으로 비교합니다.`);
  lines.push("");
  lines.push(`## 3. 최적 타일 정책`);
  lines.push(`| 모델 | 연산 | M | N | K | 타일 | Analytical cycle | 최종 cycle | PE 사용률 | 패딩 | SRAM KiB |`);
  lines.push(`|---|---|---:|---:|---:|---|---:|---:|---:|---:|---:|`);
  for (const r of res.results) {
    const s = r.shape, b = r.best;
    lines.push(`| ${s.model} | ${s.opName} | ${s.m} | ${s.n} | ${s.k} | ${b.tileM}x${b.tileN}x${b.tileK} | ${(b.rawCycles ?? b.cycles).toLocaleString()} | ${b.cycles.toLocaleString()} | ${(b.utilization*100).toFixed(1)}% | ${(b.paddingRatio*100).toFixed(1)}% | ${(b.sramBytes/1024).toFixed(1)} |`);
  }
  lines.push("", bottleneckMarkdown(res.bottlenecks), "", rooflineMarkdown(res.roofline), "", energyMarkdown(res.energy), "");
  lines.push(`## 7. 타일 선택 이유`);
  for (const r of res.results) lines.push(`- ${r.best.explanation}`);
  lines.push("", validityMarkdown(h, res.request.shapes, res.results.map(r=>r.best)), "", fusionMarkdown(analyzeFusion(res.request.shapes)), "");
  lines.push(`## 10. Estimator Suite 정보`, "```text", suite?.applied ? `활성 Estimator Suite가 적용되었습니다. samples=${suite.trainingSamples ?? "n/a"}, 평균 cycle factor=×${suite.averageCycleFactor?.toFixed?.(3) ?? "n/a"}` : "활성 Estimator Suite가 적용되지 않았습니다.", "```", "");
  lines.push(`## 11. 하드웨어 설계 조언`);
  for (const a of res.designAdvice) lines.push(`- ${a}`);
  lines.push("", `## 12. IREE 실행 명령`);
  lines.push("```bash", res.artifacts.ireeCommand ?? "생성된 IREE 명령 artifact를 확인하세요.", "```", "");
  lines.push(`## 13. 실제 적용 확인 방법`);
  lines.push(`- 가장 먼저 위의 "2-1. 실제 외부 도구 반영 상태"를 확인하세요.`);
  lines.push(`- SCALE-Sim 행이 "적용됨"이면 COMPUTE_REPORT.csv를 실제로 파싱했고, TileForge estimator 대비 cycle 비율까지 계산된 것입니다.`);
  lines.push(`- IREE compile 행이 "적용됨"이면 iree-output/model.vmfb가 실제로 생성되었고, VMFB 크기가 0보다 큽니다.`);
  lines.push(`- 하단의 "실제 외부 도구 검증 보고서"는 사용 명령, 원본 산출물 경로, cycle/VMFB 세부값을 담은 상세 부록입니다.`);
  lines.push(`- 상세 원본은 external_validation_report.md, scalesim_summary.json, iree_summary.json에서 확인할 수 있습니다.`);
  lines.push("");
  lines.push(`## 14. 생성된 산출물`);
  lines.push(`- best_tile_policy.csv: 최적 타일 정책 표`);
  lines.push(`- generated.mlir: IREE/MLIR lowering 참고용 MLIR 스케치`);
  lines.push(`- transform.mlir: Transform dialect 스케치`);
  lines.push(`- scalesim.cfg: SCALE-Sim 설정 파일`);
  lines.push(`- topology.csv: SCALE-Sim topology 입력 파일`);
  lines.push(`- manifest.json: 실행 설정 및 요약 manifest`);
  lines.push(`- policy_table.tex: 논문/보고서 삽입용 LaTeX 표`);
  lines.push(`- summary.svg: 병목 연산 요약 그래프`);
  lines.push("");
  lines.push(`## 15. 참고 사항`);
  lines.push(`이 보고서는 TileForge estimator의 예측값을 기준으로 작성됩니다. Full-pipeline을 실행하면 SCALE-Sim cycle과 IREE compile 산출물이 같은 보고서에 반영되어 예측값과 실제 외부 도구 결과를 함께 확인할 수 있습니다.`);
  return lines.join("\n");
}
