import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { loadEnvConfig } from "@next/env";

let loaded = false;

export function loadTileForgeEnv(): void {
  if (loaded) return;
  loaded = true;
  loadEnvConfig(process.cwd(), process.env.NODE_ENV !== "production", { info: () => {}, error: () => {} });
}

export function parseDotEnv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const idx = line.indexOf("=");
    if (idx < 0) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) {
      try {
        value = JSON.parse(value);
      } catch {
        value = value.slice(1, -1);
      }
    } else if (value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

export function quoteDotEnvValue(value: string): string {
  return JSON.stringify(value);
}

export function readProjectDotEnv(root = process.cwd()): Record<string, string> {
  const envPath = path.join(root, ".env");
  if (!existsSync(envPath)) return {};
  return parseDotEnv(readFileSync(envPath, "utf8"));
}

export function upsertProjectDotEnv(values: Record<string, string>, root = process.cwd(), options: { overwrite?: boolean } = {}): { path: string; created: boolean; changed: boolean; writtenKeys: string[] } {
  const envPath = path.join(root, ".env");
  const existed = existsSync(envPath);
  const original = existed ? readFileSync(envPath, "utf8") : "";
  const parsed = parseDotEnv(original);
  const lines = original ? original.replace(/\s+$/g, "").split(/\r?\n/) : [];
  const writtenKeys: string[] = [];

  if (!existed || lines.length === 0) {
    lines.push("# TileForge external tool commands");
    lines.push("# Generated by npm run setup:env. Edit these values if your tools move.");
  }

  for (const [key, value] of Object.entries(values)) {
    if (parsed[key]?.trim() && !options.overwrite) continue;
    const nextLine = `${key}=${quoteDotEnvValue(value)}`;
    const existingIndex = lines.findIndex(line => line.trim().startsWith(`${key}=`));
    if (existingIndex >= 0) lines[existingIndex] = nextLine;
    else lines.push(nextLine);
    writtenKeys.push(key);
  }

  const next = lines.join("\n") + "\n";
  const changed = next !== original;
  if (changed) writeFileSync(envPath, next, "utf8");
  return { path: envPath, created: !existed, changed, writtenKeys };
}

loadTileForgeEnv();
